<a href="https://colab.research.google.com/github/antoniehuang/colab-notebooks/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import torch
import numpy as np

## How to initialize a Tensor?
### 1. **Directly from data**

In [55]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

### 2. **From a NumPy array**

In [56]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

### 3. **From another Tensor**
The new tensor reains the properties of (ie. shape, datatype) of the argument tensor, unless explicitly overridden.

In [57]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [58]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.7611, 0.7526],
        [0.0035, 0.2947]]) 



### 4. **With random or constant values**
`shape` is a tuple of tensor dimensions.

In [59]:
shape = (2,3,) # predefine the shape of the tensor

In [60]:
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7790, 0.3195, 0.6702],
        [0.8944, 0.0912, 0.2200]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Attributes of a Tensor
Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [61]:
tensor = torch.rand(3,4)

In [62]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

In [63]:
# We move our tensor to the GPU if available
print(torch.cuda.is_available())
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

True


### **Standard numpy-like indexing and slicing**

In [64]:
tensor = torch.ones(4, 4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [65]:
print('First row:', tensor[0])

First row: tensor([1., 1., 1., 1.])


In [66]:
print('First column: ', tensor[:, 0])

First column:  tensor([1., 1., 1., 1.])


In [67]:
print('Last column:', tensor[..., -1])

Last column: tensor([1., 1., 1., 1.])


In [68]:
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### **Joining tensors**
You can use `torch.cat` to concatenate a sequence of tensors along a given dimension.



In [69]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### **Arithmetic operations**

In [70]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
print(f"y1: \n {y1} \n")

y2 = tensor.matmul(tensor.T)
print(f"y2: \n {y2} \n")

y3 = torch.rand_like(tensor)
print(f"y3: \n {y3} \n")

torch.matmul(tensor, tensor.T, out=y3)

y1: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y2: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y3: 
 tensor([[0.9337, 0.5017, 0.9905, 0.2444],
        [0.7252, 0.7183, 0.0670, 0.8308],
        [0.8517, 0.0738, 0.5482, 0.8041],
        [0.0303, 0.8655, 0.7466, 0.1238]]) 



tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [71]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### **Single-element tensors**
if you have a one-element tensor, for exmaple by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`

In [72]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


### **In-place operations**
Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [73]:
print(tensor, "\n")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [74]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

## **Bridge with NumPy**
Tensor on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

### **Tensor to NumPy array**

In [75]:
t = torch.ones(5)
print(f"t: {t}")

t: tensor([1., 1., 1., 1., 1.])


In [76]:
n = t.numpy()

In [77]:
print(f"n: {n}")

n: [1. 1. 1. 1. 1.]


In [78]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [79]:
# changing the tensor also changes the numpy array
n

array([2., 2., 2., 2., 2.], dtype=float32)

### **NumPy array to Tensor**

In [80]:
n = np.ones(5)
t = torch.from_numpy(n)

In [81]:
# Changes in the NumPy array reflects in the tensor.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
